### ISSUE TITLE
About pretrained models.

### ISSUE THREAD

**Issue by DevinXYang** [THUFutureLab/gluon-face#1]
We got some awesome results in FaceFrecognition.

Please look at our [model_zoo](https://github.com/THUFutureLab/gluon-face/wiki/Model_Zoo)

|Network|Loss|Train Dataset|Weight Norm|Feature Norm|Hyperparameter|LFW Best|Details|
|:---|:---:|:---:|:---:|:---:|:---|:---:|:----|
|mobile-facenet|ringloss|emore|Yes|No|lamda=0.01, lr=0.01, emb_size=512, batch_size=96*4|0.988167+-0.006431|Initialize of R is important, it's preferred to use a large value, like 20.|
|mobile-facenet|arcloss|emore|Yes|Yes|lr=0.01, emb_size=512, s=32, m=0.5, batch_size=128*4|0.994667+-0.004137|Finetune the model of ringloss with acc 0.988|
|se_resnet18L|arcloss|emore|Yes|Yes|lr=0.1, emb_size=512, s=64, m=0.5, batch_size=128*4|0.992167+-0.004947|Finetune the model of L2Loss with acc 0.655070|
|se_resnet50L|arcloss|emore|Yes|Yes|lr=0.1, emb_size=512, s=64, m=0.5, batch_size=(32*4)*4|0.997000+-0.002867|Finetune the model of L2Loss with acc 0.97|
|attention56-nobnprelu|arcloss|emore|Yes|Yes|lr=0.1, emb_size=256, s=64, m=0.5, batch_size=32*32|0.997000+-0.002867|Finetune the model of L2Loss at iter 5000|

InsightFace result with L-Resnet50-IR:

|Flip|False|True|
|:---|:---:|:---:|
|lfw:| 0.997167+-0.002693|**0.998167+-0.002291**|
|calfw:| 0.957833+-0.012089|**0.977583+-0.020624**|
|cplfw:| 0.886500+-0.017020|**0.943944+-0.045293**|
|cfp_fp:| 0.910571+-0.018683|**0.932960+-0.036008**|
|agedb_30:| **0.977667+-0.005925**|0.936161+-0.040025|
|cfp_ff:|**0.998286+-0.001895**|0.948447+-0.040840|

Our SE_LResnet50:

|Flip|False|True|
|:---|:---:|:---:|
|lfw:| 0.997000+-0.002867|**0.997167+-0.002587**|
|calfw:| 0.957167+-0.010410|**0.977083+-0.020488**|
|cplfw:| 0.914333+-0.013421|**0.955389+-0.033797**|
|cfp_fp:| **0.968714+-0.008438**|0.955800+-0.025998|
|agedb_30:| **0.963167+-0.008896**|0.958387+-0.023843|
|cfp_ff:|**0.997429+-0.002195**|0.964105+-0.025539|
|vgg2_fp:| 0.951400+-0.008002|**0.962209+-0.022288**|

**Comment by w510056105** [comment]
test train_arcloss.py  , then result
Traceback (most recent call last):
  File "/home/sunell/mytest/gluon-face/examples/face_recognition/train_arcloss.py", line 143, in <module>
    results = validate(net, ctx, val_datas, targets)
  File "/home/sunell/mytest/gluon-face/examples/face_recognition/utils.py", line 82, in validate
    embedding0s = [sklearn.preprocessing.normalize(e.asnumpy()) for e in embedding0s]
  File "/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/data.py", line 1546, in normalize
    estimator='the normalize function', dtype=FLOAT_DTYPES)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/utils/validation.py", line 568, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/usr/local/lib/python2.7/dist-packages/sklearn/utils/validation.py", line 56, in _assert_all_finite
    raise ValueError(msg_err.format(type_err, X.dtype))
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').
do you know why????

**Comment by PistonY** [comment]
Not support Python2.
Please use 3.6 or later.

**Comment by haoxintong** [comment]
@w510056105
We didnt test these scripts in python2, use python3.
And try `scripts/train_script.py` for training a sota model. Scripts in `examples/face_recognition` are just  tutorials of how to use gluonfr, the hyperparams here can not guarantee producing the best results. In addition, `train_arcloss.py` use mobile facenet for training, to train this network, a softmax warmup training trick is usually required, which is not implemented in the script.

**Comment by aa12356jm** [comment]
hi，you said in the wiki: **We Pre-trained model through L2-Regularization, output is cos(theta).**
what's it means?  what is **theta**?      i test the pre-trained model in ncnn,  i can get a 128 float vector,but how to comprare to another face vector? thanks

**Comment by aa12356jm** [comment]
i think that compare function should get two inputs,then calculate to get the distance of the two input vectors.  so i don not understand  **output is cos(theta)**

**Comment by haoxintong** [comment]
Hi, 
Here is the explanation for your question.
softmax is defined as follow:
![image](https://user-images.githubusercontent.com/20217439/59093837-74657400-8947-11e9-814b-8a34db9b569d.png)
For simplicity, fix b=0, then we can transform W X = ||W|| ||X|| cos (theta). When we train a face feature model, we always give a restriction to W and X, make them L2 normalized. Here we get the final loss:
![image](https://user-images.githubusercontent.com/20217439/59094291-6401c900-8948-11e9-903a-09cd44f0bb5c.png)

Many works in 2018 will follow this idea, and add margin with theta to get a better performance. How to use the output vector depends on how you train the model. In this repo, just use the L2-normalize feature, and compute either Euclidean distance or Cosine distance is ok.

With code:
```python
f1, f2 = model(faces)
f1, f2 = L2normalize(f1, f2)
similarity = euclidean_distance(f1, f2)
```

**Comment by aa12356jm** [comment]
thanks ,i got it ,  i give two pictures of two persons to  the model，and get  two vectors,  i calculate cosine distance of the two vectors.  the cosine distance is 0.9,  clearly, This is a false result .
i have tested many persons,  the cosine distance is always  0.7--0.9,  what's wrong with the results?   is it the preprocess of face image?  How to preprocess face images?   thanks

**Comment by aa12356jm** [comment]
我把模型转换到ncnn中，然后直接将人脸图像输入模型中，得到一个长度为128的向量，我将不同人的人脸图像抽取特征后进行对比，发现余弦距离非常接近，基本在0.8左右，显然这是错误的结果，我在怀疑是不是因为图像预处理的原因，我这边没有进行图像预处理，也没有看到你们有做图像归一化处理。我使用同样的方法去测试insightface的预训练模型，结果是正确的，可以帮忙分析一下原因不，谢谢

**Comment by haoxintong** [comment]
Use mtcnn get align face first.
Then do preprocess:
```python
# Converts an image NDArray of shape (H x W x C) in the range
# [0, 255] to a float32 tensor NDArray of shape (C x H x W) in
# the range [0, 1).
transform_test = transforms.Compose([
    transforms.ToTensor()
])
```
