### ISSUE TITLE
怎样输出params和json?

### ISSUE THREAD

**Issue by aa12356jm** [THUFutureLab/gluon-face#12]
你好，训练完模型之后，原始代码在训练过程中只保存了params文件，并没有json文件。我在训练过程中使用train_net.export()函数来导出params和json文件，我看了一下params有45.7MB，json文件147kb。和你给的训练好的模型对比了一下，差别好大，你给的params才3.9MB，并且你给的json文件和我导出的json文件网络结构不一样，你是怎么做的呢？麻烦指导一下哈，谢谢

**Comment by haoxintong** [comment]
net.export()出来的params包含训练时的分类层，导出的时候用`net.features.export()`就行了

**Comment by aa12356jm** [comment]
训练的过程中直接导出不行吗？我在训练过程中使用train_net.features.export(),会报错，提示如下错误：
`RuntimeError: Please first call block.hybridize() and then run forward with this block at least once before calling export`

可是已经调用这个train_net.hybridize()函数了，怎么在训练过程中导出模型呢？gluon不太熟，谢啦
可否分享一下你们将训练好的模型，重新加载然后导出的代码呢？

**Comment by DevinXYang** [comment]
初始化模型指定need_cls_layer=False,然后load参数,hybridize()再export就行了.

**Comment by haoxintong** [comment]
训练过程中用`save_parameters()`足够了，这个可以在程序意外挂掉的时候继续训练，然后在训练结束后挑一个适合部署的模型导出就好。export的目的就是为了方便使用c_api集成到其他服务或嵌入式设备上。用python写demo有网络结构源码，`load_parameters()`就够用。

对于你报错这个，添加一行`net.features.hybridize()`可以解决。具体原因是export会检查`self._cached_graph`是否为空, 父类的hybridize并没有使子类满足这个条件

用@PistonY的方法也行, 导出的模型部署时没有差别

**Comment by aa12356jm** [comment]
代码如下：
```
from gluonfr.model_zoo import get_model
train_net = get_model("mobilefacenet", classes=85742, weight_norm=True, feature_norm=True, need_cls_layer=False)
train_net.load_parameters("params/mobilefacenet-it-85500.params",ignore_extra=True)
train_net.hybridize()
train_net.export("mobilefacenet",epoch=0000)
```

报错如下：
Traceback (most recent call last):
  File "export_model.py", line 5, in <module>
    train_net.export("mobilefacenet",epoch=0000)
  File "/home/trainer/anaconda3/envs/mxnet_py36/lib/python3.6/site-packages/mxnet/gluon/block.py", line 885, in export
    "Please first call block.hybridize() and then run forward with "
RuntimeError: Please first call block.hybridize() and then run forward with this block at least once before calling export.

这个代码有啥问题吗？谢谢

**Comment by haoxintong** [comment]
因为延迟初始化,所以要跑一次forward.
`net(mx.nd.zeros(shape=(1, 3, 112, 112)))`

**Comment by aa12356jm** [comment]
可以了，非常感谢
