### ISSUE TITLE
手机端测试速度很慢？

### ISSUE THREAD

**Issue by aa12356jm** [THUFutureLab/gluon-face#13]
你好，我使用训练好的模型移植到ncnn中，在手机端（小米8 高通845处理器）测试，一张人脸图像112*112仅抽取特征要50ms左右，使用insightface提供的训练好的模型来测试，基本也是一样的时间。但是mobilefacenet的论文中给出的测试时间是25ms之内，请问你们在手机端测试过吗？为什么会有这么大的差距呢？谢谢

**Comment by haoxintong** [comment]
没做过移动端移植的工作

**Comment by aa12356jm** [comment]
我使用了这个[project](https://github.com/becauseofAI/MobileFace/tree/master/MobileFace_Identification)提供的模型MobileFace_Identification_V2-0000.params（lfw:99.65%）来测试，只需要10ms左右，感觉差别太大了，大佬帮忙分析一下原因？

**Comment by DevinXYang** [comment]
这我们也没办法呀,有空可以看一下你说的那个项目,最近没太多时间.

**Comment by haoxintong** [comment]
大概看了一下, 网络定义有一些区别, V2参数少10%, 结构窄而深, 不知道是不是这个影响

**Comment by aa12356jm** [comment]
@PistonY 理解

**Comment by DevinXYang** [comment]
> V2参数少10%

输入还是100x100的,感觉有空可以根据最近papers的研究再设计一下网络结构.

**Comment by aa12356jm** [comment]
@haoxintong 他们这样的网络设计也可以达到这么高的精度？回头试试。你们的这个mobilefacenet和官方的是一样的哈，mobilefacenet的作者在论文中给的性能指标是在高通820处理器，cpu，可以跑到24ms，我今天试了你们的模型，在高通845上需要40到50ms，只是感觉差异有点大，想分析一下原因，非常感谢你们的工作哈
