### ISSUE TITLE
prediction code?

### ISSUE THREAD

**Issue by aa12356jm** [THUFutureLab/gluon-face#16]
how get the output vector from a picture？can you provide the prediction codes?  thank you

**Comment by haoxintong** [comment]
To get face feature from original image, you need a few steps:
1. mtcnn for face detection and alignment.
2. use `net(face_image) ` to get fc output
3. compute `feature = nd.L2Normalization(fc).astype("float32").asnumpy()`

Use this feature for face verification or identification.

**Comment by aa12356jm** [comment]
thanks
