### ISSUE TITLE
Python2和Python3都支持吗？

### ISSUE THREAD

**Issue by ZHAIXINGZHAIYUE** [THUFutureLab/gluon-face#2]
Python2和Python3都支持吗？

**Comment by DevinXYang** [comment]
Only Python3.

**Comment by haoxintong** [comment]
所有代码都是在python3环境下写的, 没有考虑对python2的适配. 

python2中会出现问题的代码大概有几点:
1. pickle序列化数据的编码问题.
2. 代码写法, 如`super().__init__()`和`super(A, self).__init__()`这样的区别.
3. 库的相对引入和绝对引入之间的差异.

除了这些也有可能存在一些其他的问题, 所以最好用python3.

**Comment by ZHAIXINGZHAIYUE** [comment]
谢谢。我正打算用你们的gluon-face复现mobilefacenet。你们知道复现过程中有哪些坑是需要避免的吗？

**Comment by haoxintong** [comment]
复现网络的话基本没什么难度, 参考mobilenet_v2, 对着论文修改就行.

**Comment by ZHAIXINGZHAIYUE** [comment]
从头开始训练mobilefacenet失败，训练过程中会出现nan

**Comment by haoxintong** [comment]
参考这个: https://discuss.gluon.ai/t/topic/9959/23?u=kralkatorrik
