### ISSUE TITLE
Collection of face related papers

### ISSUE THREAD

**Issue by haoxintong** [THUFutureLab/gluon-face#22]
Moved to https://gluon-face.readthedocs.io/zh/latest/papers/index.html

----------------------

### Recognition
- [1810.09951](https://arxiv.org/abs/1810.09951) GhostVLAD for set-based face recognition

### Recognition
- [1901.05903](https://arxiv.org/abs/1901.05903) A Performance Comparison of Loss Functions for Deep Face Recognition
- [1902.11007](https://arxiv.org/abs/1902.11007) MassFace: an efficient implementation using triplet loss for face recognition
- [1904.09658](https://arxiv.org/abs/1904.09658) Probabilistic Face Embeddings

### Detection
- [1904.00386](https://arxiv.org/abs/1904.00386) PyramidBox++: High Performance Detector for Finding Tiny Face

### Others
- [1904.11685](https://arxiv.org/pdf/1904.11685) A Survey on Face Data Augmentation
- [1904.01740](https://arxiv.org/abs/1904.01740) FaceQnet: Quality Assessment for Face Recognition based on Deep Learning

**Comment by DevinXYang** [comment]
That's helpful.
