### ISSUE TITLE
自己数据集训练有错误，使用emore数据可以正常训练

### ISSUE THREAD

**Issue by aa12356jm** [THUFutureLab/gluon-face#25]
你好，我制作了自己的数据集为rec格式，但是训练的时候，有下面错误信息：
mxnet.base.MXNetError: Shape inconsistent, Provided = [440,2], inferred shape=[440,1]，
可以指导一下吗？没发现哪里出错了

**Comment by haoxintong** [comment]
有详细点的信息么, 只有这一行只知道提供的数据在经过网络计算后跟之前推理的expected shape不一致, 具体不一致的原因需要看代码.

**Comment by aa12356jm** [comment]
已经找到问题了，使用insightface中的[https://github.com/deepinsight/insightface/blob/master/src/data/face2rec2.py](url)生成rec文件时，在60行item.label = [label, item.aligned]，为什么给label 2个值？我把item.aligned去掉就可以了，在训练的时候并不需要告诉网络是否已经对齐吧？

**Comment by haoxintong** [comment]
训练时候需要哪些信息, 取决于目的是什么, 为了解决什么问题. 
举个栗子, 做对齐的时候, 会有失败的情况, 这种时候可以把原人脸图像直接添加到rec中, 由调用者在构造dataset和loader时选择是否使用对齐图像, 可以评估对齐对最终精度的影响. 网络训练虽然不需要这些信息, 但是这可以作为调参过程中控制实验条件的一部分.

**Comment by aa12356jm** [comment]
学习了，谢谢
