### ISSUE TITLE
使用不同大小的图片进行训练

### ISSUE THREAD

**Issue by 791136190** [THUFutureLab/gluon-face#29]
我们想测试一下不同分辨率的识别精度问题，如果要不同的分辨率，是不是只用修改transform函数增加一个resize，还有backbone对应修改下采样就可以了。其它有和分辨率有关的要求吗？

**Comment by haoxintong** [comment]
我个人觉得就你说的这样就可以, 改backbone会比较复杂. 原来测cifar10的时候, 改标准网络结构的方式对最终精度的影响比较大, 经常能有1%的差距.

**Comment by 791136190** [comment]
@haoxintong 是的，一旦改了backbone，对比就不是那么公平了，所以看是不是把最后一个pool直接弄成avg pool这种和size无关的，尽量减少前面的改动。感谢你的回复

**Comment by 791136190** [comment]
@haoxintong 你好，根据之前的思路进行了一些尝试，网络和输入变化的时候，对应arcloss里面的scale和margin都要进行调整，想了解一下，网络规模减少或者图片减少的时候，这两个超参数该如何调整。只能慢慢尝试吗

**Comment by haoxintong** [comment]
scale的设置在L2 Softmax上有个简单的推导, 证明了尺度参数的下限要满足一个条件: 
<img src=https://user-images.githubusercontent.com/20217439/62817512-bdfe5500-bb6a-11e9-8993-b420169c55da.png width=150/>
这里的alpha就是scale, C是类别数, P是验证准确率. 这个参数这篇文章作者的建议是不要太小或太大, 我们之前在测的时候始终用的是64, 基本没改过这个参数. 

margin的话图片数量减少可能会让网络收敛的更容易, 所以我直观感觉是最后阶段可以适当增加margin的值.

对于这两种参数网络规模影响不太大, 最后一层embedding是有关联的, arcface文章最后分析了Feature Space, 最小角度和id数量的关系.

其实相关的实验我自己做的也少, 主要是跑一次实验太久了, 没有那么多资源. 以后有机会可以慢慢补, 或者你们做过实验过来交流下结果:D
