### ISSUE TITLE
is there any different between training and not training

### ISSUE THREAD

**Issue by Wengjpv** [THUFutureLab/gluon-face#31]
thx for sharing the project,im new to fr,is there any different between training and not training?bcs i compare features gen by two different people,but the score is 0.98,that confused me a lot! what should i do?

**Comment by haoxintong** [comment]
Hi, thanks for your question.
The features should be divided by its L2 norm, then just compute their Euclidean distance. Smaller result means they are more similar faces.

**Comment by Wengjpv** [comment]
> Hi, thanks for your question.
> The features should be divided by its L2 norm, then just compute their Euclidean distance. Smaller result means they are more similar faces.

i had normalized features,and computed the cosin dis , i found that score of different faces is above 0.9, however the score should be  close to 0, bcs features of different people are orthogonal, is that right?

**Comment by haoxintong** [comment]
There is no difference to compute cosine distance or euclidean distance if you have normalized the features. I'm not sure whether you are computing cosine distance or cosine similarity, which will get opposite result.

And if distance function is not your problem, check if you have done pre-process like face alignment and pixel range from 0-255 to 0-1. They are necessary for model testing.

**Comment by Wengjpv** [comment]
i found that i did not do preprocessing, and that maybe the reason, btw whats yr preprocessing mothod?i tried to normalize img by
mean = mx.nd.array([123.675, 116.28, 103.53]).reshape((1, 1, 1, 3))
scale = mx.nd.array([58.395, 57.12, 57.375]).reshape((1, 1, 1, 3))
is that reasonable?

**Comment by haoxintong** [comment]
We usually use:
```python
img = img.astype("float32") / 255
img = nd.transpose(img, (2,0,1))
```
The input size of image should be (N, 3, 112,112).

**Comment by Wengjpv** [comment]
you have totally solved my problem,thanks again for your sharing, have a nice day! lol
