### ISSUE TITLE
update pip installation

### ISSUE THREAD

**Issue by ThomasDelteil** [THUFutureLab/gluon-face#33]
Could you please release the current version to 1.0.2, the model_zoo package is still missing at this point that would be helpful to have it in the pip release.

**Comment by DevinXYang** [comment]
I will do this later but please have a look at this #34 . I think this is the last update.

**Comment by DevinXYang** [comment]
For now please use `pip install git+https://github.com/THUFutureLab/gluon-face.git@master`

**Comment by DevinXYang** [comment]
I've finished uploading new version of this.
https://pypi.org/project/gluonfr/1.0.2/

**Comment by ThomasDelteil** [comment]
Thanks for doing this 👍
