### ISSUE TITLE
为什么在examples中有些LOSS要对features和weights做L2归一化？？

### ISSUE THREAD

**Issue by bigbao9494** [THUFutureLab/gluon-face#5]
NormDense中有些LOSS会对features和weights做L2归一化后再用全连接来分类？

class NormDense(HybridBlock):
    # noinspection PyMethodOverriding
    def hybrid_forward(self, F, x, weight, *args, **kwargs):
        if self._weight_norm:
            weight = F.L2Normalization(weight, mode='instance')
        if self._feature_norm:
            x = F.L2Normalization(x, mode='instance', name='fc1n')
        return F.FullyConnected(data=x, weight=weight, no_bias=True,
                                num_hidden=self._classes, name='fc7')

**Comment by haoxintong** [comment]
全连接层的公式Wx=||W||⋅||x||⋅cosθ, 在对features和weights做归一化之后, 就可以约束网络学习特征之间的角度距离, 很多损失函数都是从这个角度来做的.
具体的解释可以参考NormFace, Coco Loss, ArcFace这些论文中的相关章节.

**Comment by bigbao9494** [comment]
非常感谢，想再请教一个问题：

想请问一下，在GLUON中如何来实现MXNET中的网络可视化呢？试了一下GLUON的网络无法像下面这样使用mx.viz.

#显示网络的参数情况：我们将调用MXNet中的viz库,需要先告知MXNet输入数据的格式
shape = {“data”: (1,1,28,28)}
mx.viz.print_summary(symbol=net,shape=shape)
mx.viz.plot_network(symbol=net,shape=shape).view() #显示网络的结构图

**Comment by haoxintong** [comment]
命令式的用`net.summary()`
```python
net = nn.HybridSequential()
net.add(nn.Dense(10),
        nn.Dense(10),
        nn.Dense(10))

net.initialize()
net.summary(nd.ones(shape=(1, 5)))
```
符号式的用`mx.viz.plot_network()`
```python
...
net.hybridize()
x = mx.sym.var('data')
sym = net(x)
mx.viz.plot_network(sym).view()
```

**Comment by bigbao9494** [comment]
非常感谢，终于找到在GLUON下的方法 了，感觉还是没有MXNET下的PDF 显示出来那样直观
