### ISSUE TITLE
关于center_loss的疑问

### ISSUE THREAD

**Issue by bigbao9494** [THUFutureLab/gluon-face#6]
在center_loss中为了可视化：
增加一个(256,2)的全连接层来学习出坐标x,y，用它来和中心点计算center_loss
增加的这个全连接层形状输出是(batch,2)，后面接分类的全连接层后输出是(batch,10)
就是把256通道变成2个通道，再由2个通道变成10个通道(10分类，10个数字)，
网络结构通道都是图像减小通道数增加的过程，现在为了可视化最后2层变成了
通道急剧减少然后再增加，这个过程会不会影响最后一层信息的流动啊？
难道这样不影响分类？？

**Comment by haoxintong** [comment]
最后用2维特征接分类肯定是会影响最终精度的，但是我们的主要目的是做可视化，这种方式比先学习再降维更直观。
