### ISSUE TITLE
与inisightFace处理FC7层不一样

### ISSUE THREAD

**Issue by bigbao9494** [THUFutureLab/gluon-face#7]
代码中处理FC7层权重的学习率和权重衰减与insightFace不一样
insightFace中是单独对FC7层权重做了学习率和权重衰减的：
_weight = mx.symbol.Variable("fc7_weight", shape=(args.num_classes, args.emb_size), lr_mult=args.fc7_lr_mult, wd_mult=args.fc7_wd_mult)
但是gluon-face是做的全局学习率和权重衰减

**Comment by bigbao9494** [comment]
@haoxintong 能帮助回答一下？

**Comment by haoxintong** [comment]
这个算是调参的问题, 我们做这个项目的初衷是做算法和相关资源的汇集, 展现的效果就是利用Gluon的接口能够达到目前SOTA的精度 + 实现简单. 至于调参的细节, 在写代码时是没有刻意和paper实现保持一致. 

像fc7这种其实是在全局的lr和wd基础上添加了一个mult超参, 利用gluon的方法很容易实现和扩展:
```python
class NormDense(HybridBlock):
    def __init__(self, classes, weight_norm=False, feature_norm=False, 
                 lr_mult=1.0, wd_mult=1.0,
                 dtype='float32', weight_initializer=None, in_units=0, **kwargs):
        super().__init__(**kwargs)
        ...
        ...
        with self.name_scope():
            self.weight = self.params.get('weight', shape=(classes, in_units),
                                          init=weight_initializer, dtype=dtype,
                                          lr_mult=lr_mult, wd_mult=wd_mult,
                                          allow_deferred_init=True)
        ...
```
考虑更复杂的策略, 也可以根据这个[例子](http://zh.diveintodeeplearning.org.s3-website-us-west-2.amazonaws.com/chapter_computer-vision/fine-tuning.html#%E5%AE%9A%E4%B9%89%E5%92%8C%E5%88%9D%E5%A7%8B%E5%8C%96%E6%A8%A1%E5%9E%8B)中的`collect_params().setattr('lr_mult', 10)`, 在这个基础上去写就可以.

**Comment by bigbao9494** [comment]
收到，非常 感谢 ！！
