### ISSUE TITLE
unittest of your lossess

### ISSUE THREAD

**Issue by yumc-afk** [THUFutureLab/gluon-face#8]
请问 有写关于这些loss的单元测试吗，这样的话修改和学习都会方便很多呢

**Comment by haoxintong** [comment]
其实开始的时候有考虑单元测试, 不过最后没有实践, 感觉单纯的验证loss输出这种形式意义不大.
不知道是不是我对unit test的理解还不够深, 如果你有什么建议可以讲一下, 学习学习.

**Comment by DevinXYang** [comment]
写测试模块意义太小,没法用CI.
