### ISSUE TITLE
为什么没有做softmax的预训练?

### ISSUE THREAD

**Issue by bigbao9494** [THUFutureLab/gluon-face#9]
insightFace训练过程是分两步,先做softmax的预训练再做arcLoss训练

**Comment by haoxintong** [comment]
训练流程看个人经验, 怎么做都行, 最终精度差别不大

**Comment by gehaocool** [comment]
arcface的additive angular margin loss不需要做softmax预训练

**Comment by bigbao9494** [comment]
> arcface的additive angular margin loss不需要做softmax预训练

为什么？？

**Comment by haoxintong** [comment]
一般用softmax做预训练是因为改进的Loss在网络训练初期不稳定, 所以这是一种加快训练的策略, 对于ArcLoss来说, 属于可以做但是不必要.
